package com.daily.mybatis.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_article
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ArticleWithBLOBs extends Article {
    /**
     * Database Column Remarks:
     *   标题图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.title_pictrues
     *
     * @mbggenerated
     */
    private String title_pictrues;

    /**
     * Database Column Remarks:
     *   文章简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.title_mini
     *
     * @mbggenerated
     */
    private String title_mini;

    /**
     * Database Column Remarks:
     *   文章内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.articelContent
     *
     * @mbggenerated
     */
    private String articelContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.title_pictrues
     *
     * @return the value of t_article.title_pictrues
     *
     * @mbggenerated
     */
    public String getTitle_pictrues() {
        return title_pictrues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.title_pictrues
     *
     * @param title_pictrues the value for t_article.title_pictrues
     *
     * @mbggenerated
     */
    public void setTitle_pictrues(String title_pictrues) {
        this.title_pictrues = title_pictrues == null ? null : title_pictrues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.title_mini
     *
     * @return the value of t_article.title_mini
     *
     * @mbggenerated
     */
    public String getTitle_mini() {
        return title_mini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.title_mini
     *
     * @param title_mini the value for t_article.title_mini
     *
     * @mbggenerated
     */
    public void setTitle_mini(String title_mini) {
        this.title_mini = title_mini == null ? null : title_mini.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.articelContent
     *
     * @return the value of t_article.articelContent
     *
     * @mbggenerated
     */
    public String getArticelContent() {
        return articelContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.articelContent
     *
     * @param articelContent the value for t_article.articelContent
     *
     * @mbggenerated
     */
    public void setArticelContent(String articelContent) {
        this.articelContent = articelContent == null ? null : articelContent.trim();
    }
}