package com.daily.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_article
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Article {
    /**
     * Database Column Remarks:
     *   博客主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.articleId
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.publishTime
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.userId
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   文章标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.articelTitle
     *
     * @mbggenerated
     */
    private String articelTitle;

    /**
     * Database Column Remarks:
     *   关联标签id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.categoryId
     *
     * @mbggenerated
     */
    private String categoryId;

    /**
     * Database Column Remarks:
     *   文章类型/暂定 1是轮播图文章
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.articleId
     *
     * @return the value of t_article.articleId
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.articleId
     *
     * @param articleId the value for t_article.articleId
     *
     * @mbggenerated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.publishTime
     *
     * @return the value of t_article.publishTime
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.publishTime
     *
     * @param publishTime the value for t_article.publishTime
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.userId
     *
     * @return the value of t_article.userId
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.userId
     *
     * @param userId the value for t_article.userId
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.articelTitle
     *
     * @return the value of t_article.articelTitle
     *
     * @mbggenerated
     */
    public String getArticelTitle() {
        return articelTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.articelTitle
     *
     * @param articelTitle the value for t_article.articelTitle
     *
     * @mbggenerated
     */
    public void setArticelTitle(String articelTitle) {
        this.articelTitle = articelTitle == null ? null : articelTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.categoryId
     *
     * @return the value of t_article.categoryId
     *
     * @mbggenerated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.categoryId
     *
     * @param categoryId the value for t_article.categoryId
     *
     * @mbggenerated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.type
     *
     * @return the value of t_article.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.type
     *
     * @param type the value for t_article.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}