package com.daily.mybatis.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_article_tag
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ArticleTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_tag.tag_id
     *
     * @mbggenerated
     */
    private String tag_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_tag.article_id
     *
     * @mbggenerated
     */
    private String article_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_tag.tag_id
     *
     * @return the value of t_article_tag.tag_id
     *
     * @mbggenerated
     */
    public String getTag_id() {
        return tag_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_tag.tag_id
     *
     * @param tag_id the value for t_article_tag.tag_id
     *
     * @mbggenerated
     */
    public void setTag_id(String tag_id) {
        this.tag_id = tag_id == null ? null : tag_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_tag.article_id
     *
     * @return the value of t_article_tag.article_id
     *
     * @mbggenerated
     */
    public String getArticle_id() {
        return article_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_tag.article_id
     *
     * @param article_id the value for t_article_tag.article_id
     *
     * @mbggenerated
     */
    public void setArticle_id(String article_id) {
        this.article_id = article_id == null ? null : article_id.trim();
    }
}