package com.daily.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_article
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.articleId
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.publishTime
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.userId
     *
     * @mbggenerated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.categoryId
     *
     * @mbggenerated
     */
    private String categoryId;

    /**
     * Database Column Remarks:
     *   博客列表缩略图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.title_pictrues
     *
     * @mbggenerated
     */
    private String title_pictrues;

    /**
     * Database Column Remarks:
     *   文章摘要
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.title_mini
     *
     * @mbggenerated
     */
    private String title_mini;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.articleId
     *
     * @return the value of t_article.articleId
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.articleId
     *
     * @param articleId the value for t_article.articleId
     *
     * @mbggenerated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.publishTime
     *
     * @return the value of t_article.publishTime
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.publishTime
     *
     * @param publishTime the value for t_article.publishTime
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.userId
     *
     * @return the value of t_article.userId
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.userId
     *
     * @param userId the value for t_article.userId
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.categoryId
     *
     * @return the value of t_article.categoryId
     *
     * @mbggenerated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.categoryId
     *
     * @param categoryId the value for t_article.categoryId
     *
     * @mbggenerated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.title_pictrues
     *
     * @return the value of t_article.title_pictrues
     *
     * @mbggenerated
     */
    public String getTitle_pictrues() {
        return title_pictrues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.title_pictrues
     *
     * @param title_pictrues the value for t_article.title_pictrues
     *
     * @mbggenerated
     */
    public void setTitle_pictrues(String title_pictrues) {
        this.title_pictrues = title_pictrues == null ? null : title_pictrues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.title_mini
     *
     * @return the value of t_article.title_mini
     *
     * @mbggenerated
     */
    public String getTitle_mini() {
        return title_mini;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.title_mini
     *
     * @param title_mini the value for t_article.title_mini
     *
     * @mbggenerated
     */
    public void setTitle_mini(String title_mini) {
        this.title_mini = title_mini == null ? null : title_mini.trim();
    }
}