package com.daily.mybatis.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_tag
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   标签名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.create_time
     *
     * @mbggenerated
     */
    private Date create_time;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tag.delete_status
     *
     * @mbggenerated
     */
    private Integer delete_status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.id
     *
     * @return the value of t_tag.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.id
     *
     * @param id the value for t_tag.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.name
     *
     * @return the value of t_tag.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.name
     *
     * @param name the value for t_tag.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.create_time
     *
     * @return the value of t_tag.create_time
     *
     * @mbggenerated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.create_time
     *
     * @param create_time the value for t_tag.create_time
     *
     * @mbggenerated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tag.delete_status
     *
     * @return the value of t_tag.delete_status
     *
     * @mbggenerated
     */
    public Integer getDelete_status() {
        return delete_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tag.delete_status
     *
     * @param delete_status the value for t_tag.delete_status
     *
     * @mbggenerated
     */
    public void setDelete_status(Integer delete_status) {
        this.delete_status = delete_status;
    }
}