package com.daily.mybatis.dao;

import com.daily.mybatis.entity.ArticleTag;
import com.daily.mybatis.entity.ArticleTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    int countByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    int deleteByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String tag_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    int insert(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    int insertSelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    List<ArticleTag> selectByExample(ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    ArticleTag selectByPrimaryKey(String tag_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ArticleTag record, @Param("example") ArticleTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleTag record);
}